# Use an official Node runtime as the base image
FROM node:18.13 AS builder

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json /app/

# Install the application dependencies
RUN npm install
# Copy the rest of the application code to the working directory
COPY ./ /app/

# Build the Angular app
RUN npm run build -- --output-path=./dist/out --configuration=development

FROM nginx:1.15.8-alpine
COPY --from=builder /app/dist/out/ /usr/share/nginx/html

EXPOSE 80 443
