
services:
  ang-app:
    build:
      context: ./ang-app
      dockerfile: Dockerfile.angular
    container_name: ang-app
    image: angular-app:latest
    volumes:
      - ./ang-app:/app     
    
    expose:
      - "80"
    networks:
      - apinetwork

  api1:
    image: apiexample
    container_name: api1
    build:
      context: ./YipYip.DockerWebAPI
      dockerfile: Docker/Dockerfile.angular
    environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
    expose:
      - "8080"
    networks:
      - apinetwork
  api2:
    image: apiexample
    container_name: api2
    environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080 
    expose:
      - "8080"
    networks:
      - apinetwork
    depends_on:
      - api1      

  proxy:    
    image: reverse-proxy:latest
    container_name: proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile.proxy
    ports:
      - "80:80"
      - "81:81"
             # Exposes the reverse proxy to the host
    # volumes:
    #   - ./nginx/nginx-reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - apinetwork
    depends_on:      
      - ang-app
      - api1
      - api2
 
  seqlog:
    image: datalust/seq:latest
    container_name: seqlog
    restart: always
    build:
      context: ./seq  # Path to directory containing Dockerfile.seqlog
      dockerfile: Dockerfile.seq
    environment:
      ACCEPT_EULA: "Y"
      #SEQ_API_LISTENURIS: http://seqlog:5341  # Correctly formatted URI for listening on port 8000
      #SEQ_SERVER_URL: http://seqlog:80 
      # SEQ_BASE_URI: /seqlog
    depends_on:
      - proxy
    ports:
      - 8000:80      
      - 5341:5341
    networks:
      - apinetwork
  
      

networks:
  apinetwork:
    driver: bridge

