
services:
  api1:
    image: webapiexample
    container_name: api1
    build:
      context: ./YipYip.DockerWebAPI
      dockerfile: Docker/Dockerfile
    environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
    expose:
      - "8080"
    networks:
      - apinetwork
  api2:
    image: webapiexample
    container_name: api2
    environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080 
    expose:
      - "8080"
    networks:
      - apinetwork
    depends_on:
      - api1      

  proxy:
    container_name: proxy
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - apinetwork
    depends_on:
      - api1
      - api2
  # gui:
  #   container_name: gui
  #   build:
  #     context: ./GUI
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "80:80"
  #   networks:
  #     - apinetwork
  #   depends_on:
  #     - proxy
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y # Required to accept Seq's end-user license agreement
    expose:
      - "80" # Web UI and ingestion
    networks:
      - apinetwork
    depends_on:
      - proxy  
      

networks:
  apinetwork:
    driver: bridge
